import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
// import "@/styles/css/satoshi.css";
import "react-toastify/dist/ReactToastify.css";
import AppProvider from "@/components/AppProvider/AppProvider";
import { cookies } from "next/headers";
import { NextUIProvider } from "@nextui-org/react";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
    title: "Long Tam Pharmacy",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookiesStore = cookies();
    const sessionToken = cookiesStore.get("sessionToken");
    return (
        <html lang="en">
            <body className={inter.className} suppressHydrationWarning={true}>
                <div className="dark:bg-boxdark-2 dark:text-bodydark">
                    <NextUIProvider>
                        <AppProvider initialSessionToken={sessionToken?.value}>{children}</AppProvider>
                    </NextUIProvider>
                    <ToastContainer autoClose={3000} />
                </div>
            </body>
        </html>
    );
}
