name: GitHub Actions CI
run-name: CI for NextJS
on:
    pull_request:
    workflow_dispatch:
    push:
        branches:
            - "develop"
            - "main"
jobs:
    NextJS-Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set Node.js 20
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Setup yarn
              run: npm install -g yarn

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Check linting
              run: yarn lint

            # - name: Run test
            #   run: yarn test

            - name: Build Next.js app
              run: yarn build

    Push-To-Image-Repo:
        if: github.ref_name == 'main'
        needs: NextJS-Build
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: hrm-fe
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DO_TOKEN }}

            - name: Authen DO registry
              run: doctl registry login

            - name: Build docker image
              run: docker build . -t ${{ env.IMAGE_NAME }}:latest

            - name: Tag image with DO
              run: docker tag hrm-fe:latest registry.digitalocean.com/capstone-registry/${{ env.IMAGE_NAME }}:latest

            - name: Push image to registry
              run: docker push registry.digitalocean.com/capstone-registry/${{ env.IMAGE_NAME }}:latest
